In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/home/shawaiz/Desktop/Data_sets/customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
2    70  Female     Good        PG        No
11   74    Male     Good        UG       Yes
27   69  Female     Poor        PG        No
8    65  Female  Average        UG        No
31   22  Female     Poor    School       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [7]:
X_train

review education
23     Good    School
31     Poor    School
4   Average        UG
28     Poor    School
0   Average    School
39     Poor        PG
48     Good        UG
37  Average        PG
10     Good        UG
3      Good        PG
22     Poor        PG
43     Poor        PG
45     Poor        PG
27     Poor        PG
6      Good    School
16     Poor        UG
11     Good        UG
19     Poor        PG
36     Good        UG
33     Good        PG
29  Average        UG
21  Average        PG
5   Average    School
14     Poor        PG
1      Poor        UG
40     Good    School
32  Average        UG
42     Good        PG
17     Poor        UG
41     Good        PG
12     Poor    School
26     Poor        PG
15     Poor        UG
47     Good        PG
2      Good        PG
9      Good        UG
20  Average    School
13  Average    School
8   Average        UG
34  Average    School

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [10]:
# train k uper fit krty hen but transform train pay b krna ha and fit pay bhi
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [12]:
X_train

array([[2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.]])

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit(y_train)

LabelEncoder()

In [17]:
# here the "No" is "zero (0)" & "Yes" is "1"
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(y_train)
y_test =le.transform(y_test)

In [19]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0])

In [20]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0])